# Generated by Django 2.2 on 2019-05-08 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opisanie', models.TextField()),
                ('zvezdi', models.IntegerField()),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField()),
                ('phone', models.IntegerField()),
                ('Vk', models.TextField()),
                ('Insta', models.TextField()),
                ('Status', models.CharField(max_length=20)),
                ('DateReg', models.DateField()),
                ('DataLast', models.DateTimeField()),
                ('Zamoroz', models.BooleanField()),
                ('Balans', models.FloatField()),
                ('Email', models.TextField()),
                ('name', models.CharField(max_length=300)),
                ('PhotoPerson', models.TextField(null=True)),
                ('Bird', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('DateAdd', models.DateTimeField()),
                ('DateEdit', models.DateTimeField()),
                ('Sex', models.BooleanField(null=True)),
                ('seazon', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Opisanie', models.TextField()),
                ('DateAdd', models.DateTimeField()),
                ('DateEdit', models.DateTimeField()),
                ('Sex', models.CharField(max_length=20, null=True)),
                ('seazon', models.CharField(max_length=20, null=True)),
                ('Material', models.TextField(null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTovars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VidArendi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VidArendiTovars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoimost', models.FloatField()),
                ('vikup', models.IntegerField()),
                ('Vozvrat', models.IntegerField()),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar')),
                ('vidArendi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendi')),
            ],
        ),
        migrations.CreateModel(
            name='VidArendiSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoimost', models.FloatField()),
                ('Vozvrat', models.IntegerField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Set')),
                ('vidArendi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendi')),
            ],
        ),
        migrations.CreateModel(
            name='TovarsSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skidka', models.FloatField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Set')),
                ('tovars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar')),
            ],
        ),
        migrations.CreateModel(
            name='TovarPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('size', models.CharField(max_length=20)),
                ('VidArendiTovars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.VidArendiTovars')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='tovar',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.TypeTovars'),
        ),
        migrations.CreateModel(
            name='SizeTovars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=20)),
                ('Tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar')),
            ],
        ),
        migrations.CreateModel(
            name='SetsPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('stoimost', models.FloatField()),
                ('vikup', models.IntegerField()),
                ('Vozvrat', models.IntegerField()),
                ('Set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Set')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person')),
                ('vidArendi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendi')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTovara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FilePathField()),
                ('main', models.BooleanField(null=True)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puth', models.FilePathField()),
                ('Main', models.BooleanField(null=True)),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Set')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOtzyv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyth', models.FilePathField()),
                ('otz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Otziv')),
            ],
        ),
        migrations.AddField(
            model_name='otziv',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person'),
        ),
        migrations.AddField(
            model_name='otziv',
            name='Set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Set'),
        ),
        migrations.AddField(
            model_name='otziv',
            name='Tovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar'),
        ),
        migrations.CreateModel(
            name='oplata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Sum', models.FloatField()),
                ('Set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.SetsPerson')),
                ('tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.TovarPerson')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='LikePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person')),
                ('sets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Set')),
                ('tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Tovar')),
            ],
        ),
    ]
