# Generated by Django 2.2 on 2019-05-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_vidarenditovars_vikup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovarperson',
            name='VidArendiTovars',
        ),
    ]
