# Generated by Django 2.2 on 2019-05-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_remove_tovarperson_vidarenditovars'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovarperson',
            name='VidArendiTovars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.VidArendiTovars'),
        ),
    ]
