# Generated by Django 2.2 on 2019-05-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_tovarperson_vidarenditovars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oplata',
        ),
    ]
