# Generated by Django 2.2 on 2019-05-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_delete_oplata'),
    ]

    operations = [
        migrations.CreateModel(
            name='oplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Sum', models.FloatField()),
                ('Set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.SetsPerson')),
                ('tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.TovarPerson')),
            ],
        ),
    ]
