# Generated by Django 2.2 on 2019-05-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_oplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oplate',
            new_name='oplata',
        ),
    ]
