# Generated by Django 2.2 on 2019-05-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20190508_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePerson',
        ),
    ]
