# Generated by Django 2.2 on 2019-05-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_opration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opration',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
