# Generated by Django 2.2 on 2019-05-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_auto_20190515_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoSets',
        ),
    ]
