# Generated by Django 2.2 on 2019-05-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_photosets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photosets',
            name='Main',
        ),
    ]
