# Generated by Django 2.2 on 2019-05-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_remove_photosets_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosets',
            name='Main',
            field=models.BooleanField(null=True),
        ),
    ]
