# Generated by Django 2.2 on 2019-05-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_photosets_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setsperson',
            name='Set',
        ),
        migrations.RemoveField(
            model_name='setsperson',
            name='Vozvrat',
        ),
        migrations.RemoveField(
            model_name='setsperson',
            name='stoimost',
        ),
        migrations.RemoveField(
            model_name='setsperson',
            name='vidArendi',
        ),
        migrations.RemoveField(
            model_name='setsperson',
            name='vikup',
        ),
        migrations.AddField(
            model_name='setsperson',
            name='size',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setsperson',
            name='vidarendisets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.VidArendiSets'),
        ),
        migrations.AddField(
            model_name='vidarendisets',
            name='vikup',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
