# Generated by Django 2.2 on 2019-05-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_auto_20190515_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='Nalichie',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
