# Generated by Django 2.2 on 2019-05-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_tovar_nalichie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidarenditovars',
            name='Vozvrat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vidarenditovars',
            name='vikup',
            field=models.IntegerField(null=True),
        ),
    ]
