# Generated by Django 2.2 on 2019-05-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_auto_20190520_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='SezonTovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Seaz')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Set')),
                ('tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar')),
            ],
        ),
        migrations.DeleteModel(
            name='SeazTovar',
        ),
    ]
