# Generated by Django 2.2 on 2019-05-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_auto_20190520_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sezontovar',
            old_name='name',
            new_name='seaz',
        ),
    ]
