# Generated by Django 2.2 on 2019-05-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_auto_20190520_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SezonTovar',
        ),
    ]
