# Generated by Django 2.2 on 2019-05-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_sezontovar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarTypeTovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='photosets',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='type',
        ),
        migrations.AddField(
            model_name='phototovara',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Set'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='Del',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phototovara',
            name='tovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar'),
        ),
        migrations.DeleteModel(
            name='PhotoOtzyv',
        ),
        migrations.DeleteModel(
            name='PhotoSets',
        ),
        migrations.AddField(
            model_name='tovartypetovar',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar'),
        ),
        migrations.AddField(
            model_name='tovartypetovar',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.TypeTovars'),
        ),
    ]
