# Generated by Django 2.2 on 2019-05-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0031_auto_20190520_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tovartypetovar',
            old_name='type',
            new_name='typpe',
        ),
    ]
