# Generated by Django 2.2 on 2019-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_auto_20190521_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototovara',
            name='photo',
            field=models.FilePathField(),
        ),
    ]
