# Generated by Django 2.2 on 2019-05-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_auto_20190521_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Adress',
            field=models.TextField(default='Район  Есенина, улица Каруселина, дом тоже Каруселина'),
            preserve_default=False,
        ),
    ]
