# Generated by Django 2.2 on 2019-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0036_person_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='otziv',
            name='Status',
            field=models.TextField(default='Принят'),
            preserve_default=False,
        ),
    ]
