# Generated by Django 2.2 on 2019-05-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_otziv_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='otziv',
            name='Otvet',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
