# Generated by Django 2.2 on 2019-05-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_otziv_otvet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otziv',
            name='Otvet',
            field=models.TextField(null=True),
        ),
    ]
