# Generated by Django 2.2 on 2019-05-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_auto_20190524_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otziv',
            name='delete',
        ),
    ]
