# Generated by Django 2.2 on 2019-05-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0042_otziv_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otziv',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
