# Generated by Django 2.2 on 2019-05-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0043_auto_20190525_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='otziv',
            name='nameperson',
            field=models.TextField(null=True),
        ),
    ]
