# Generated by Django 2.2 on 2019-05-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0044_otziv_nameperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otziv',
            name='Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person'),
        ),
        migrations.AlterField(
            model_name='otziv',
            name='delete',
            field=models.BooleanField(null=True),
        ),
    ]
