# Generated by Django 2.2 on 2019-05-26 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0045_auto_20190525_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Adress',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Balans',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Bird',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='DataLast',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='DateReg',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Insta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Vk',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Zamoroz',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
