# Generated by Django 2.2 on 2019-05-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0046_auto_20190526_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('money', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('money', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='opration',
            name='person',
        ),
        migrations.RemoveField(
            model_name='setsperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='setsperson',
            name='vidarendisets',
        ),
        migrations.RemoveField(
            model_name='vidarendisets',
            name='set',
        ),
        migrations.RemoveField(
            model_name='vidarendisets',
            name='vidArendi',
        ),
        migrations.RemoveField(
            model_name='vidarenditovars',
            name='Vozvrat',
        ),
        migrations.AddField(
            model_name='sizetovars',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizetovars',
            name='nalichie',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovarperson',
            name='Vozvrat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tovarperson',
            name='countPaid',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vidarenditovars',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Set'),
        ),
        migrations.AlterField(
            model_name='vidarenditovars',
            name='tovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar'),
        ),
        migrations.AlterField(
            model_name='vidarenditovars',
            name='vikup',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='oplata',
        ),
        migrations.DeleteModel(
            name='opration',
        ),
        migrations.DeleteModel(
            name='SetsPerson',
        ),
        migrations.DeleteModel(
            name='VidArendiSets',
        ),
        migrations.AddField(
            model_name='paid',
            name='tovPer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.TovarPerson'),
        ),
        migrations.AddField(
            model_name='addpaid',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.TovarPerson'),
        ),
    ]
