# Generated by Django 2.2 on 2019-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0047_auto_20190528_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovarperson',
            name='Vozvrat',
        ),
        migrations.AddField(
            model_name='vidarenditovars',
            name='Vozvrat',
            field=models.FloatField(null=True),
        ),
    ]
