# Generated by Django 2.2 on 2019-05-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0048_auto_20190528_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Balans',
        ),
    ]
