# Generated by Django 2.2 on 2019-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0049_remove_person_balans'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpaid',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paid',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
