# Generated by Django 2.2 on 2019-05-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0051_auto_20190529_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpaid',
            name='plusminus',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addpaid',
            name='tovPer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.TovarPerson'),
        ),
        migrations.DeleteModel(
            name='Paid',
        ),
    ]
