# Generated by Django 2.2 on 2019-06-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0054_auto_20190608_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizetovars',
            name='count',
        ),
        migrations.CreateModel(
            name='AddTovars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Person')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Size')),
                ('tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Tovar')),
            ],
        ),
    ]
