# Generated by Django 2.2 on 2019-06-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0055_auto_20190608_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtovars',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.SizeTovars'),
        ),
    ]
