# Generated by Django 2.2 on 2019-06-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0056_auto_20190608_1725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizetovars',
            unique_together={('Size',)},
        ),
    ]
