# Generated by Django 2.2 on 2019-06-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0057_auto_20190610_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='Nalichie',
        ),
    ]
