# Generated by Django 2.2 on 2019-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0059_auto_20190610_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidarenditovars',
            name='platej',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
