# Generated by Django 2.2 on 2019-06-11 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0060_vidarenditovars_platej'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizetovars',
            unique_together=set(),
        ),
    ]
