# Generated by Django 2.2 on 2019-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0062_auto_20190611_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototovara',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
