# Generated by Django 2.2 on 2019-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0063_auto_20190611_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototovara',
            name='delete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
