# Generated by Django 2.2 on 2019-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0064_phototovara_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtovars',
            name='PlusMinus',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
