# Generated by Django 2.2 on 2019-06-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0065_addtovars_plusminus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovarperson',
            name='VidArendiTovars',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendiTovars'),
            preserve_default=False,
        ),
    ]
