# Generated by Django 2.2 on 2019-06-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0066_auto_20190614_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpaid',
            name='tovPer',
        ),
        migrations.CreateModel(
            name='SpsPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('plusminus', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('money', models.FloatField()),
                ('tovPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.TovarPerson')),
            ],
        ),
    ]
