# Generated by Django 2.2 on 2019-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0069_remove_tovarperson_countpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
