# Generated by Django 2.2 on 2019-06-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0071_manager_tovarsvidach_vidacha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TovarsKorzine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Korzina')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendiTovars')),
            ],
        ),
        migrations.DeleteModel(
            name='TovarsVidach',
        ),
    ]
