# Generated by Django 2.2 on 2019-06-15 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0072_auto_20190615_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korzina',
            name='date',
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='vidacha',
            name='zakaz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Zakaz'),
            preserve_default=False,
        ),
    ]
