# Generated by Django 2.2 on 2019-06-15 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0073_auto_20190615_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarsZakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendiTovars')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Zakaz')),
            ],
        ),
    ]
