# Generated by Django 2.2 on 2019-06-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0074_tovarszakaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovarszakaz',
            name='size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='firstapp.SizeTovars'),
            preserve_default=False,
        ),
    ]
