# Generated by Django 2.2 on 2019-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0075_tovarszakaz_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='nomer',
            field=models.TextField(default='fsdf1231f'),
            preserve_default=False,
        ),
    ]
