# Generated by Django 2.2 on 2019-06-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0076_zakaz_nomer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zakaz',
            unique_together={('nomer',)},
        ),
    ]
