# Generated by Django 2.2 on 2019-06-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0077_auto_20190616_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpaid',
            name='tovPer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.TovarPerson'),
        ),
        migrations.DeleteModel(
            name='SpsPaid',
        ),
    ]
