# Generated by Django 2.2 on 2019-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0078_auto_20190616_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpaid',
            name='status',
            field=models.BooleanField(),
        ),
    ]
