# Generated by Django 2.2 on 2019-06-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0079_auto_20190616_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovarperson',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.SizeTovars'),
        ),
    ]
