# Generated by Django 2.2 on 2019-06-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0080_auto_20190617_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovarperson',
            name='size',
            field=models.TextField(),
        ),
    ]
