# Generated by Django 2.2 on 2019-06-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0081_auto_20190617_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
