# Generated by Django 2.2 on 2019-06-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0082_zakaz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
