# Generated by Django 2.2 on 2019-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0083_auto_20190619_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='vidann',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('Email',)},
        ),
    ]
