# Generated by Django 2.2 on 2019-04-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosets',
            name='Main',
            field=models.BooleanField(null=True),
        ),
    ]
