# Generated by Django 2.2 on 2019-05-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_person_photoperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='PhotoPerson',
            field=models.TextField(null=True),
        ),
    ]
