# Generated by Django 2.2 on 2019-05-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20190503_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovarperson',
            name='Vozvrat',
        ),
        migrations.RemoveField(
            model_name='tovarperson',
            name='stoimost',
        ),
        migrations.RemoveField(
            model_name='tovarperson',
            name='tovar',
        ),
        migrations.RemoveField(
            model_name='tovarperson',
            name='vidArendi',
        ),
        migrations.CreateModel(
            name='VidArendiTovars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoimost', models.FloatField()),
                ('Vozvrat', models.IntegerField()),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Tovar')),
                ('vidArendi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendi')),
            ],
        ),
    ]
