# Generated by Django 2.2 on 2019-05-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20190503_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='Price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovarperson',
            name='DateAdd',
            field=models.DateTimeField(default='2016-11-29T09:00:00+03:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovarperson',
            name='VidArendiTovars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.VidArendiTovars'),
        ),
        migrations.CreateModel(
            name='oplata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Sum', models.FloatField()),
                ('Set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.SetsPerson')),
                ('tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.TovarPerson')),
            ],
        ),
    ]
