# Generated by Django 2.2 on 2019-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20190504_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='tovarperson',
            name='DateAdd',
        ),
        migrations.AddField(
            model_name='vidarenditovars',
            name='vikup',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
