# Generated by Django 2.2 on 2019-05-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20190504_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovarperson',
            name='size',
            field=models.CharField(default='S', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LikePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.SetsPerson')),
                ('tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.TovarPerson')),
            ],
        ),
    ]
