# Generated by Django 2.2 on 2019-05-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20190504_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeperson',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Bird',
            field=models.DateField(default='1999-03-03'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likeperson',
            name='sets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Set'),
        ),
        migrations.AlterField(
            model_name='likeperson',
            name='tovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.Tovar'),
        ),
    ]
