# Generated by Django 2.2 on 2019-05-07 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20190506_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='setsperson',
            name='Vozvrat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setsperson',
            name='stoimost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setsperson',
            name='vidArendi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.VidArendi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setsperson',
            name='vikup',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
